modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage2"
license="MIT"
[[mods]]
modId="refinedstorage2"
version="${version}"
displayName="Refined Storage 2"
displayURL="https://github.com/refinedmods/refinedstorage2"
logoFile="icon.png"
authors = "Refined Mods"
description = '''
Refined Storage is a mass storage mod for Minecraft that offers the player a network-based storage system, allowing them to store items and fluids on a massively expandable device network.
'''
