name: Draft release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
      version-number:
        description: 'Version number'
        required: false
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITFLOW_PUSH_TOKEN }}
      - name: Get latest version from changelog
        if: "${{ github.event.inputs.version-number == '' }}"
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md
      - name: Get version number to release (Semver)
        if: "${{ github.event.inputs.version-number == '' }}"
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.changelog.outputs.version }}
          level: ${{ github.event.inputs.release-type }}
      - name: Assign version number to release (Semver)
        if: "${{ github.event.inputs.version-number == '' }}"
        run: |
          echo "VERSION=${{ steps.bump-semver.outputs.new_version }}" >> $GITHUB_ENV
      - name: Assign version number to release (manual)
        if: "${{ github.event.inputs.version-number != '' }}"
        run: |
          echo "VERSION=${{ github.event.inputs.version-number }}" >> $GITHUB_ENV
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ env.VERSION }}
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'CHANGELOG.md'
          default_author: github_actions
          message: 'chore: prepare release v${{ env.VERSION }}'
          new_branch: 'release/${{ env.VERSION }}'
          push: true
      - name: Create pull request for release
        uses: thomaseizinger/create-pull-request@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ env.VERSION }}
          base: main
          title: Release v${{ env.VERSION }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will publish the release.